version: '3.8'

services: 
    db:
        image: postgres
        ports: 
            - "5432:5432"
    
    jenkins:
        image: jenkins/jenkins
        ports: 
            - "8080:8080"
            - "50000:50000"
        depends_on: 
            - db
    
    myimage:
        image:  darkhalf/devops
        ports: 
            - "80"